{"uuid": "a399eac6-ea75-4433-abd2-65caa28d1707", "children": ["83930591-fe07-494b-8c89-5209d3f19d7f", "268f2232-039e-44c6-bac1-d7bdcb15fc8c", "a6760ea0-082e-49b1-b893-bbd6116d4181", "d564ab90-b67e-4c44-8553-c98a2f127ba8", "5bbaf02e-0962-44d8-bcdd-27aef140fbba", "6d5fa799-71df-4ee5-9509-3e88736a27d6", "701d2702-2375-41f3-8956-ec011f8296b7", "d90e4182-8a26-4dc1-a1b1-b4a370de43bc", "47476c4e-a9e6-4f7b-a8dd-613e1883b3dd", "e27e179c-d05e-46bd-b003-8d2a0ff343a6", "4e3389fa-35ec-4399-acb8-6d8ce2d8d91c", "addb5713-043c-447f-919b-7780cea1fe41", "43509e6b-19a9-450a-b568-c3ddb6c59e35", "a9bbc928-b946-46b7-8b75-a42ffb501fc9"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000\n  (Session info: MicrosoftEdge=130.0.2849.80)\nStacktrace:\n#0 0x55e7d04775be <unknown>\n#1 0x55e7cff3e9f6 <unknown>\n#2 0x55e7cff286e8 <unknown>\n#3 0x55e7cff284b2 <unknown>\n#4 0x55e7cff2699e <unknown>\n#5 0x55e7cff26e14 <unknown>\n#6 0x55e7cff3b097 <unknown>\n#7 0x55e7cff4a4ff <unknown>\n#8 0x55e7cff4f2fb <unknown>\n#9 0x55e7cff27405 <unknown>\n#10 0x55e7cff4a190 <unknown>\n#11 0x55e7cffcbd42 <unknown>\n#12 0x55e7cffadcf3 <unknown>\n#13 0x55e7cff7e2de <unknown>\n#14 0x55e7cff7efbe <unknown>\n#15 0x55e7d044c521 <unknown>\n#16 0x55e7d044f791 <unknown>\n#17 0x55e7d044f20b <unknown>\n#18 0x55e7d044fbc5 <unknown>\n#19 0x55e7d043def2 <unknown>\n#20 0x55e7d044ff4d <unknown>\n#21 0x55e7d04278c5 <unknown>\n#22 0x55e7d0467d18 <unknown>\n#23 0x55e7d0467f2f <unknown>\n#24 0x55e7d04761bc <unknown>\n#25 0x7fd3b1694ac3 <unknown>\n\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 906, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Common/BaseClass.py\", line 97, in driver\n    driver.maximize_window()\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 499, in maximize_window\n    self.execute(command, None)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1732000581567, "stop": 1732000919842}, {"name": "driver", "status": "passed", "start": 1732000920910, "stop": 1732000921856}], "afters": [{"name": "driver::0", "status": "passed", "start": 1732000971774, "stop": 1732000971848}], "start": 1732000920910, "stop": 1732000971848}