{"uuid": "8a288658-df2f-4311-b5df-db5bb74c292c", "children": ["e61a6f03-4634-4654-89f4-d8d2db4d483c", "714d3e87-9d3d-4a6d-8f20-b5c0ac38f7e6", "178300d4-9f00-42bd-aa6a-c433c6b5dc78", "92a228bb-0af7-4af8-b4ee-d431089b2544", "14d0fcdc-4b56-49ac-8e5c-6d911ff5a487", "42e6e53c-30a6-4317-9bd4-117c7cd5cb0c", "bd074254-0bd4-42f8-99ed-0d992f143d74", "ec609527-8097-4de6-909b-2f2127d2bd78", "8a6f4925-d3c1-4dda-8ece-3876da4f6bcd", "b7b2009d-0b97-4440-b167-908c8c3c97b5", "4da19a29-e46c-4523-ac84-b77a19653a8c", "999bac33-535c-43de-b52d-08297cef6412", "eedd8e25-35b3-4cd4-a4e7-ed12b6e52233", "9dafebd6-a091-431d-b8d1-a258abf27f2e"], "befores": [{"name": "get_sponsors_page_content", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//label[contains(.,'logos')]/../../..//span[@class ='sc-dkPtRN cSldSA']\"}\n  (Session info: chrome=131.0.6778.69); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x561b56ddf4ca <unknown>\n#1 0x561b568f2620 <unknown>\n#2 0x561b56941306 <unknown>\n#3 0x561b569415a1 <unknown>\n#4 0x561b56986a04 <unknown>\n#5 0x561b5696539d <unknown>\n#6 0x561b56983de0 <unknown>\n#7 0x561b56965113 <unknown>\n#8 0x561b56933be0 <unknown>\n#9 0x561b56934bbe <unknown>\n#10 0x561b56dabe4b <unknown>\n#11 0x561b56dafde2 <unknown>\n#12 0x561b56d98d2c <unknown>\n#13 0x561b56db0957 <unknown>\n#14 0x561b56d7e4bf <unknown>\n#15 0x561b56dce348 <unknown>\n#16 0x561b56dce510 <unknown>\n#17 0x561b56dde346 <unknown>\n#18 0x7fed33c94ac3 <unknown>\n\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 913, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Tests/test_SponsorsPage.py\", line 27, in get_sponsors_page_content\n    TestSponsorsPage.sponsors_page_content = admin_obj.get_sponsors_page_content()\n                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Pages/Admin.py\", line 358, in get_sponsors_page_content\n    \"logos\": self.get_sponsors_logos_filenames(),\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Pages/Admin.py\", line 320, in get_sponsors_logos_filenames\n    filenames.append(self.driver.find_element(*self.sponsors_logo_filename).text)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1732000600679, "stop": 1732000621611}, {"name": "get_sponsors_page_content", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"(//span[.='Content Manager'])[1]/..\"}\n  (Session info: chrome=131.0.6778.69); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x561b56ddf4ca <unknown>\n#1 0x561b568f2620 <unknown>\n#2 0x561b56941306 <unknown>\n#3 0x561b569415a1 <unknown>\n#4 0x561b56986a04 <unknown>\n#5 0x561b5696539d <unknown>\n#6 0x561b56983de0 <unknown>\n#7 0x561b56965113 <unknown>\n#8 0x561b56933be0 <unknown>\n#9 0x561b56934bbe <unknown>\n#10 0x561b56dabe4b <unknown>\n#11 0x561b56dafde2 <unknown>\n#12 0x561b56d98d2c <unknown>\n#13 0x561b56db0957 <unknown>\n#14 0x561b56d7e4bf <unknown>\n#15 0x561b56dce348 <unknown>\n#16 0x561b56dce510 <unknown>\n#17 0x561b56dde346 <unknown>\n#18 0x7fed33c94ac3 <unknown>\n\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 913, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Tests/test_SponsorsPage.py\", line 27, in get_sponsors_page_content\n    TestSponsorsPage.sponsors_page_content = admin_obj.get_sponsors_page_content()\n                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Pages/Admin.py\", line 353, in get_sponsors_page_content\n    self.click_content_manager_button()\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Pages/Admin.py\", line 100, in click_content_manager_button\n    self.driver.find_element(*self.content_manager_button).click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1732000622685, "stop": 1732000634210}, {"name": "get_sponsors_page_content", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"(//span[.='Content Manager'])[1]/..\"}\n  (Session info: chrome=131.0.6778.69); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x561b56ddf4ca <unknown>\n#1 0x561b568f2620 <unknown>\n#2 0x561b56941306 <unknown>\n#3 0x561b569415a1 <unknown>\n#4 0x561b56986a04 <unknown>\n#5 0x561b5696539d <unknown>\n#6 0x561b56983de0 <unknown>\n#7 0x561b56965113 <unknown>\n#8 0x561b56933be0 <unknown>\n#9 0x561b56934bbe <unknown>\n#10 0x561b56dabe4b <unknown>\n#11 0x561b56dafde2 <unknown>\n#12 0x561b56d98d2c <unknown>\n#13 0x561b56db0957 <unknown>\n#14 0x561b56d7e4bf <unknown>\n#15 0x561b56dce348 <unknown>\n#16 0x561b56dce510 <unknown>\n#17 0x561b56dde346 <unknown>\n#18 0x7fed33c94ac3 <unknown>\n\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 913, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Tests/test_SponsorsPage.py\", line 27, in get_sponsors_page_content\n    TestSponsorsPage.sponsors_page_content = admin_obj.get_sponsors_page_content()\n                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Pages/Admin.py\", line 353, in get_sponsors_page_content\n    self.click_content_manager_button()\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Pages/Admin.py\", line 100, in click_content_manager_button\n    self.driver.find_element(*self.content_manager_button).click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1732000635242, "stop": 1732000646520}, {"name": "get_sponsors_page_content", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"(//span[.='Content Manager'])[1]/..\"}\n  (Session info: chrome=131.0.6778.69); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x561b56ddf4ca <unknown>\n#1 0x561b568f2620 <unknown>\n#2 0x561b56941306 <unknown>\n#3 0x561b569415a1 <unknown>\n#4 0x561b56986a04 <unknown>\n#5 0x561b5696539d <unknown>\n#6 0x561b56983de0 <unknown>\n#7 0x561b56965113 <unknown>\n#8 0x561b56933be0 <unknown>\n#9 0x561b56934bbe <unknown>\n#10 0x561b56dabe4b <unknown>\n#11 0x561b56dafde2 <unknown>\n#12 0x561b56d98d2c <unknown>\n#13 0x561b56db0957 <unknown>\n#14 0x561b56d7e4bf <unknown>\n#15 0x561b56dce348 <unknown>\n#16 0x561b56dce510 <unknown>\n#17 0x561b56dde346 <unknown>\n#18 0x7fed33c94ac3 <unknown>\n\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 913, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Tests/test_SponsorsPage.py\", line 27, in get_sponsors_page_content\n    TestSponsorsPage.sponsors_page_content = admin_obj.get_sponsors_page_content()\n                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Pages/Admin.py\", line 353, in get_sponsors_page_content\n    self.click_content_manager_button()\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Pages/Admin.py\", line 100, in click_content_manager_button\n    self.driver.find_element(*self.content_manager_button).click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1732000647551, "stop": 1732000658817}], "start": 1732000647551, "stop": 1732000658859}