{"uuid": "cdaaeb20-8090-46af-a5e7-db811778895d", "children": ["7d99438b-ae60-4751-a1ca-997432db51b6", "7a7f4f7f-620a-4892-94a2-a07588fca00e", "cef8dbb1-b0ca-413f-b619-a84706973dec", "b8117634-d36d-4fe4-b8dc-6f9302f4cdd0", "debd0c8b-d53f-4125-be90-fe4aa9ee2147", "96024249-a490-4f87-8d7f-e22a51a53fd1", "482521aa-2733-4b7e-8199-cdf81eb2a6ed", "c995d1c3-7617-427d-ac13-5f354a737aca", "22d2331f-9e04-42d8-bc38-78330993e4dc", "73a8e900-26ff-4fb3-892d-a94888df207a", "e15394ce-fe9e-4e3b-b97a-1afa51840c81", "870de18a-a430-4d68-bb7f-29a29e515775", "6c2c8546-7e66-4910-a280-c73d95f0b9a1", "39e5f933-3117-4579-b0fe-c4996df61e81"], "befores": [{"name": "get_sponsors_page_content", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//label[contains(.,'logos')]/../../..//span[@class ='sc-dkPtRN cSldSA']\"}\n  (Session info: chrome=131.0.6778.69); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x559941d0b4ca <unknown>\n#1 0x55994181e620 <unknown>\n#2 0x55994186d306 <unknown>\n#3 0x55994186d5a1 <unknown>\n#4 0x5599418b2a04 <unknown>\n#5 0x55994189139d <unknown>\n#6 0x5599418afde0 <unknown>\n#7 0x559941891113 <unknown>\n#8 0x55994185fbe0 <unknown>\n#9 0x559941860bbe <unknown>\n#10 0x559941cd7e4b <unknown>\n#11 0x559941cdbde2 <unknown>\n#12 0x559941cc4d2c <unknown>\n#13 0x559941cdc957 <unknown>\n#14 0x559941caa4bf <unknown>\n#15 0x559941cfa348 <unknown>\n#16 0x559941cfa510 <unknown>\n#17 0x559941d0a346 <unknown>\n#18 0x7f2501c94ac3 <unknown>\n\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 913, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Tests/test_SponsorsPage.py\", line 27, in get_sponsors_page_content\n    TestSponsorsPage.sponsors_page_content = admin_obj.get_sponsors_page_content()\n                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Pages/Admin.py\", line 358, in get_sponsors_page_content\n    \"logos\": self.get_sponsors_logos_filenames(),\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Pages/Admin.py\", line 320, in get_sponsors_logos_filenames\n    filenames.append(self.driver.find_element(*self.sponsors_logo_filename).text)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1732001289186, "stop": 1732001316506}, {"name": "get_sponsors_page_content", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//label[contains(.,'logos')]/../../..//span[@class ='sc-dkPtRN cSldSA']\"}\n  (Session info: chrome=131.0.6778.69); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x559941d0b4ca <unknown>\n#1 0x55994181e620 <unknown>\n#2 0x55994186d306 <unknown>\n#3 0x55994186d5a1 <unknown>\n#4 0x5599418b2a04 <unknown>\n#5 0x55994189139d <unknown>\n#6 0x5599418afde0 <unknown>\n#7 0x559941891113 <unknown>\n#8 0x55994185fbe0 <unknown>\n#9 0x559941860bbe <unknown>\n#10 0x559941cd7e4b <unknown>\n#11 0x559941cdbde2 <unknown>\n#12 0x559941cc4d2c <unknown>\n#13 0x559941cdc957 <unknown>\n#14 0x559941caa4bf <unknown>\n#15 0x559941cfa348 <unknown>\n#16 0x559941cfa510 <unknown>\n#17 0x559941d0a346 <unknown>\n#18 0x7f2501c94ac3 <unknown>\n\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 913, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Tests/test_SponsorsPage.py\", line 27, in get_sponsors_page_content\n    TestSponsorsPage.sponsors_page_content = admin_obj.get_sponsors_page_content()\n                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Pages/Admin.py\", line 358, in get_sponsors_page_content\n    \"logos\": self.get_sponsors_logos_filenames(),\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Pages/Admin.py\", line 320, in get_sponsors_logos_filenames\n    filenames.append(self.driver.find_element(*self.sponsors_logo_filename).text)\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1732001317581, "stop": 1732001342263}, {"name": "get_sponsors_page_content", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"(//span[.='Content Manager'])[1]/..\"}\n  (Session info: chrome=131.0.6778.69); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x559941d0b4ca <unknown>\n#1 0x55994181e620 <unknown>\n#2 0x55994186d306 <unknown>\n#3 0x55994186d5a1 <unknown>\n#4 0x5599418b2a04 <unknown>\n#5 0x55994189139d <unknown>\n#6 0x5599418afde0 <unknown>\n#7 0x559941891113 <unknown>\n#8 0x55994185fbe0 <unknown>\n#9 0x559941860bbe <unknown>\n#10 0x559941cd7e4b <unknown>\n#11 0x559941cdbde2 <unknown>\n#12 0x559941cc4d2c <unknown>\n#13 0x559941cdc957 <unknown>\n#14 0x559941caa4bf <unknown>\n#15 0x559941cfa348 <unknown>\n#16 0x559941cfa510 <unknown>\n#17 0x559941d0a346 <unknown>\n#18 0x7f2501c94ac3 <unknown>\n\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 913, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Tests/test_SponsorsPage.py\", line 27, in get_sponsors_page_content\n    TestSponsorsPage.sponsors_page_content = admin_obj.get_sponsors_page_content()\n                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Pages/Admin.py\", line 353, in get_sponsors_page_content\n    self.click_content_manager_button()\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Pages/Admin.py\", line 100, in click_content_manager_button\n    self.driver.find_element(*self.content_manager_button).click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1732001343296, "stop": 1732001364432}, {"name": "get_sponsors_page_content", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"(//span[.='Content Manager'])[1]/..\"}\n  (Session info: chrome=131.0.6778.69); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x559941d0b4ca <unknown>\n#1 0x55994181e620 <unknown>\n#2 0x55994186d306 <unknown>\n#3 0x55994186d5a1 <unknown>\n#4 0x5599418b2a04 <unknown>\n#5 0x55994189139d <unknown>\n#6 0x5599418afde0 <unknown>\n#7 0x559941891113 <unknown>\n#8 0x55994185fbe0 <unknown>\n#9 0x559941860bbe <unknown>\n#10 0x559941cd7e4b <unknown>\n#11 0x559941cdbde2 <unknown>\n#12 0x559941cc4d2c <unknown>\n#13 0x559941cdc957 <unknown>\n#14 0x559941caa4bf <unknown>\n#15 0x559941cfa348 <unknown>\n#16 0x559941cfa510 <unknown>\n#17 0x559941d0a346 <unknown>\n#18 0x7f2501c94ac3 <unknown>\n\n", "trace": "  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 166, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pluggy/_callers.py\", line 102, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1132, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/_pytest/fixtures.py\", line 913, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Tests/test_SponsorsPage.py\", line 27, in get_sponsors_page_content\n    TestSponsorsPage.sponsors_page_content = admin_obj.get_sponsors_page_content()\n                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Pages/Admin.py\", line 353, in get_sponsors_page_content\n    self.click_content_manager_button()\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Pages/Admin.py\", line 100, in click_content_manager_button\n    self.driver.find_element(*self.content_manager_button).click()\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 741, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1732001365464, "stop": 1732001386976}], "start": 1732001365464, "stop": 1732001387019}