{"name": "Unsuccessfully login with email: simeon.hhl.qagmail.com and password: Test#1234", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "self = <Tests.test_Login.TestLogin object at 0x7fa1ce89bad0>\ndriver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"a5426876-fd15-4636-8c75-4ae97a6858be\")>\nemail = 'simeon.hhl.qagmail.com', password = 'Test#1234'\nerror = 'Please enter a valid email', test_case = 'C58783'\n\n    @severity(severity_level.NORMAL)\n    @allure.feature('Login')\n    @allure.title(\"Unsuccessfully login with email: {email} and password: {password}\")\n    @allure.issue(\"QP-382\", \"Story QP-382\")\n    @allure.issue(\"QP-356\", \"Epic QP-356\")\n    @allure.testcase(\"58783\", \"C58783\")\n    @allure.testcase(\"58784\", \"C58784\")\n    @allure.testcase(\"58785\", \"C58785\")\n    @allure.testcase(\"58785\", \"C58786\")\n    @pytest.mark.dependency(depends=[\"test_1\"])\n    @pytest.mark.parametrize('email,password,error,test_case', [\n        (EMAIL[:-1], PASSWORD, \"There was a problem logging you in. Please try again.\", \"C58784\"),\n        (EMAIL, PASSWORD[:-1], \"There was a problem logging you in. Please try again.\", \"C58785\"),\n        (EMAIL.replace(\"@\", \"\"), PASSWORD, \"Please enter a valid email\", \"C58783\"),\n        (\"\", PASSWORD, \"Please enter your email\", \"C58784\"),\n        (EMAIL, \"\", \"Please enter your password\", \"C58785\")\n    ])\n    def test_3(self, driver, email, password, error, test_case):\n        current_browser = self.current_browser\n        login_obj = Login(driver)\n        driver.refresh()\n        login_obj.set_email_field(email, current_browser)\n        login_obj.set_password_field(password, current_browser)\n        with check, allure.step(f\"{test_case}: Check for error\"):\n            if \"Please enter\" in error:\n>               assert login_obj.is_filed_error_message_visible()\n\nTests/test_Login.py:80: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \nPages/LoginPage.py:53: in is_filed_error_message_visible\n    message = wait.until(EC.visibility_of_element_located(self.field_error_message))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"a5426876-fd15-4636-8c75-4ae97a6858be\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x7fa1ce3119e0>\nmessage = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException"}, "steps": [{"name": "C58783: Check for error", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Tests/test_Login.py\", line 80, in test_3\n    assert login_obj.is_filed_error_message_visible()\n  File \"/home/runner/work/QUBA_WEB/QUBA_WEB/Pages/LoginPage.py\", line 53, in is_filed_error_message_visible\n    message = wait.until(EC.visibility_of_element_located(self.field_error_message))\n              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.11/x64/lib/python3.11/site-packages/selenium/webdriver/support/wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1734076816470, "stop": 1734076847997}], "parameters": [{"name": "email", "value": "'simeon.hhl.qagmail.com'"}, {"name": "password", "value": "'Test#1234'"}, {"name": "error", "value": "'Please enter a valid email'"}, {"name": "test_case", "value": "'C58783'"}, {"name": "driver", "value": "'firefox'"}], "start": 1734076812774, "stop": 1734076847998, "uuid": "ffb37e63-6356-4e29-bddd-842dbf664138", "historyId": "be6ec85270b6ccb73c33ab53bad98d52", "testCaseId": "96b2e665285a8ec417094929a80fdfda", "fullName": "Tests.test_Login.TestLogin#test_3", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Login"}, {"name": "tag", "value": "dependency(depends=['test_1'])"}, {"name": "tag", "value": "flaky(reruns=3, reruns_delay=1)"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "fv-az1913-369"}, {"name": "thread", "value": "1941-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_Login"}], "links": [{"type": "tms", "url": "https://hedgehoglabqa.testrail.io/index.php?/cases/view/58785", "name": "C58786"}, {"type": "tms", "url": "https://hedgehoglabqa.testrail.io/index.php?/cases/view/58785", "name": "C58785"}, {"type": "tms", "url": "https://hedgehoglabqa.testrail.io/index.php?/cases/view/58784", "name": "C58784"}, {"type": "tms", "url": "https://hedgehoglabqa.testrail.io/index.php?/cases/view/58783", "name": "C58783"}, {"type": "issue", "url": "https://hedgehog-lab.atlassian.net/browse/QP-356", "name": "Epic QP-356"}, {"type": "issue", "url": "https://hedgehog-lab.atlassian.net/browse/QP-382", "name": "Story QP-382"}]}